### PR TITLE
Feature/caleb/mobile footer

### PR DESCRIPTION
**Pull request by cng04**

### CODE REVIEW

**Review by JonZ21 — CHANGES_REQUESTED** [review]
Screenshot 2024-11-02 at 1 43 18 PM

looks good. could you make the gmail, instagram, youtube etc icons a bit bigger?


also the wrapping on the "liuisaac/Mecha_Mayhem_App/issues" is a bit funky on some sizes. maybe we can just change it to a hyperlink with the text "report a bug".

Screenshot 2024-11-02 at 1 44 43 PM

**Comment by cng04** [comment]
Do I link "liuisaac/Mecha_Mayhem_App/issues" to https://github.com/liuisaac/Mecha_Mayhem_App_2024/issues

**Comment by JonZ21** [comment]
> Do I link "liuisaac/Mecha_Mayhem_App/issues" to https://github.com/liuisaac/Mecha_Mayhem_App_2024/issues

sheesh. It's closed LOL. Just remove the thing for now

**Comment by cng04** [comment]
is there a way to push additional commits to this pr
Screen Shot 2024-11-02 at 5 18 21 PM

**Review by JonZ21 — APPROVED** [review]
lgtm!

**Pull request merged**
